#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# STAGES — B 组（Cloudflare staging 资源开通）。
# 说明：资源创建是真实动作；wrangler 使用仓库本地 node_modules。
# 生成的值写入仓库根 .env（gitignored）；wrangler.jsonc 只在本向导确认后替换 staging 占位符。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE="${ENV_FILE:-.env}"
GAPS=()
W="npx wrangler"

banner "Cloudflare staging B 组开通向导"

# ── Stage 1：账户授权 ─────────────────────────────────────────────────────
stage "账户授权与登录（浏览器）"
say "仅使用 staging 账户；不要在此登录 production 凭据。"
open_url "https://dash.cloudflare.com/"
step "方式 A（推荐）：另开终端执行 'npx wrangler login'，浏览器授权完成后回到这里按 Enter。"
step "方式 B（非交互）：用 API Token（模板 Edit Cloudflare Workers）；粘贴到下方隐藏输入，写入 .env 并导出。"
ask_secret CLOUDFLARE_API_TOKEN "粘贴 API Token（或回车跳走，改用 wrangler login）"
if [[ -n "$CLOUDFLARE_API_TOKEN" ]]; then
  write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
  export CLOUDFLARE_API_TOKEN
fi
step "授权核验：wrangler whoami 应显示账户（非交互场景则显示 token 上下文）。"
$W whoami >/dev/null 2>&1 || { warn "wrangler 未授权；若刚选 wrangler login，应当时已完成。"; }
if ! $W whoami >/dev/null 2>&1; then
  say "未通过授权（gap）：请先完成登录/token 再运行本向导其余阶段。"
fi

# ── Stage 2：创建 D1 ─────────────────────────────────────────────────────
stage "创建 staging D1 数据库（实际资源）"
# $W d1 create → 抓 database_id 回填 .env（嵌入式提取，无需人工复制）
if $W d1 create enso-monitor-staging 2>&1 | tee /tmp/.d1-create.log; then
  D1_DATABASE_ID_STAGING=$(grep -oE "[0-9a-f]{32}" /tmp/.d1-create.log 2>/dev/null | head -1 || true)
  if [[ -z "$D1_DATABASE_ID_STAGING" ]]; then
    D1_DATABASE_ID_STAGING=$(grep -oE '[0-9a-f]{32}' /tmp/.d1-create.log | head -1 || true)
  fi
else
  warn "d1 create 失败；请按提示核对权限或用 dashboard 手动创建。"
fi
if [[ -n "${D1_DATABASE_ID_STAGING:-}" ]]; then
  write_env D1_DATABASE_ID_STAGING "$D1_DATABASE_ID_STAGING"
  export D1_DATABASE_ID_STAGING
else
  warn "未自动提取到 D1 ID；请在 dashboard 复制后用下一步手动粘贴。"
fi

# ── Stage 3：创建 R2 ─────────────────────────────────────────────────────
stage "创建 staging R2 存储桶（实际资源）"
step "运行 npx wrangler r2 bucket create enso-raw-staging + 命名已经写死（staging 专用）。"
if $W r2 bucket create enso-raw-staging 2>&1; then
  note "R2 enso-raw-staging ✓"
else
  warn "R2 bucket create 失败（可能同名已存在）。"
fi

# ── Stage 4：回填 wrangler.jsonc ─────────────────────────────────────────
stage "把 D1 ID 回填 wrangler.jsonc staging 段（真实替换占位符）"
if [[ -n "${D1_DATABASE_ID_STAGING:-}" ]]; then
  sed -i.bak "s/00000000-0000-0000-0000-000000000001/${D1_DATABASE_ID_STAGING}/" wrangler.jsonc
  note "staging database_id：$D1_DATABASE_ID_STAGING ✓ wrangler.jsonc 已更新"
  rm -f wrangler.jsonc.bak
else
  warn "没有 D1 ID 回填，可能需要手动处理。"
fi

# ── Stage 5：C 组 Access 三值 ────────────────────────────────────────────
stage "C 组 Access 三值（issuer / audience / JWKS URL）"
say "来自 C 组回执 track；staging 与 production 数值不同。"
ask ACCESS_JWT_ISSUER "issuer（例 https://xxx.cloudflareaccess.com）"
ask ACCESS_JWT_AUDIENCE "audience（Access Aud claim）"
ask ACCESS_JWKS_URL "JWKS URL"
if [[ -n "$ACCESS_JWT_ISSUER" ]]; then
  write_env ACCESS_JWT_ISSUER "$ACCESS_JWT_ISSUER"
  write_env ACCESS_JWT_AUDIENCE "${ACCESS_JWT_AUDIENCE:-}"
  write_env ACCESS_JWKS_URL "${ACCESS_JWKS_URL:-}"
fi

# ── Stage 6：三个测试身份 ────────────────────────────────────────────────
open_url "https://one.dash.cloudflare.com/"
stage "C 组三个测试身份（Access）"
step "为 staging Access 建 3 个角色身份：viewer / editor / publisher（各一账户）。"
step "config 用最小权限设计：viewer 只读，editor 写草稿，publisher 发布/撤回。"
if confirm "三个测试身份已可在 staging Access 下作用？"; then
  note "已确认。"
else
  GAPS+=("三个测试身份待建")
fi

# ── Stage 7：告警邮箱与域名 ──────────────────────────────────────────────
stage "B4/B6：域名与告警接收邮箱"
ask ALERT_EMAIL_C "告警接收邮箱"
ask STAGING_DOMAIN "staging 域名（没有就回车记录缺口）"
if [[ -n "$ALERT_EMAIL_C" ]]; then
  write_env ALERT_EMAIL_C "$ALERT_EMAIL_C"
  write_env STAGING_DOMAIN "${STAGING_DOMAIN:-}"
fi
[[ -n "${STAGING_DOMAIN:-}" ]] || GAPS+=("staging 域名（B4）")

# ── Stage 8：deploy + healthz ────────────────────────────────────────────
if confirm "现在用 wrangler deploy --env staging 创建并部署 staging Worker（运行真实命令）？"; then
  stage "staging 部署与健康检查"
  $W d1 migrations apply enso-monitor-staging --remote --env staging || warn "migrations 失败，核对 D1 ID 后单独运行"
  npx wrangler deploy --env staging 2>&1 | tail -3
  note "健康检查：用 deploy 输出的 workers.dev URL 访问 /api/v1/healthz（应返回 ok）；"
  note "/api/admin/* 未经 Access 配置时返回 503 AUTH_CONFIGURATION（预期 fail-closed）。"
  pause "healthz 确认后按 Enter"
else
  warn "本阶段跳过 —— staging Worker 未部署（不算缺口，下一轮再做）。"
fi

finish
