#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
EVIDENCE_DIR="$REPO_ROOT/.local-evidence"
EVIDENCE_FILE="$EVIDENCE_DIR/cloudflare-staging-preflight-$(date -u +%Y%m%dT%H%M%SZ).md"
GAPS=()

umask 077
mkdir -p "$EVIDENCE_DIR"
chmod 700 "$EVIDENCE_DIR"
{
  printf '# Cloudflare staging 只读前置检查证据\n\n'
  printf -- '- 运行时间（UTC）：%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf -- '- 范围：仅人工 dashboard/文档核验；未执行部署、资源变更、密钥读取或 CLI 远端操作。\n'
  printf -- '- 数据最小化：本文件只记录确认状态与非敏感预算选择；不记录账户/资源 ID、域名、token、JWT、cookie、密钥或日志正文。\n\n'
  printf '| 阶段 | 结论 |\n| --- | --- |\n'
} > "$EVIDENCE_FILE"

record_result() {
  local label="$1" result="$2"
  printf '| %s | %s |\n' "$label" "$result" >> "$EVIDENCE_FILE"
}

confirm_stage() {
  local label="$1" question="$2"
  if confirm "$question"; then
    record_result "$label" "confirmed"
    say "已记录非敏感结论：confirmed。"
  else
    record_result "$label" "gap-or-unknown"
    GAPS+=("$label")
    warn "已记录为缺口；不要在此向导中修复或更改 Cloudflare 设置。"
  fi
}

finish_preflight() {
  _clear
  printf '\n%s%s  前置检查结束%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#GAPS[@]} )); then
    note "已记录 ${#GAPS[@]} 个 gap-or-unknown；它们必须在独立获授权流程中处理。"
  else
    note "本次人工确认未报告缺口；这不构成 staging 演练、部署、计费或生产发布批准。"
  fi
  note "本向导仅写入最小化的本地证据文件，未执行任何 Cloudflare 远端操作。"
  printf '\n'
}

choose_budget_status() {
  local reply=""
  while true; do
    say "仅记录预算/计费决定状态，不输入套餐、金额、账户或付款信息。"
    printf '  %s? 预算与付费决定 [free/paid/deferred/unknown] ' "$YELLOW"
    read -r reply || true
    case "$reply" in
      free|paid|deferred|unknown)
        record_result "预算与付费决定" "$reply"
        [[ "$reply" == "free" || "$reply" == "paid" ]] || GAPS+=("预算与付费决定")
        return 0
        ;;
      *) warn "请输入 free、paid、deferred 或 unknown。" ;;
    esac
  done
}

banner "Cloudflare staging 只读前置检查"

stage "账户授权与 staging 资源隔离"
say "只浏览 dashboard；不要创建资源、改变成员角色、触碰账单、复制账户 ID，或打开 API Token 页面。"
open_url "https://dash.cloudflare.com/"
open_url "https://developers.cloudflare.com/fundamentals/manage-members/roles/"
step "在你已获授权的账户上下文中，确认当前身份仅用于这次只读检查，并按最小权限原则查看。"
step "仅目视核对 staging Worker、D1、R2 与 production 名称/账户边界不同；不要记录或粘贴任何 ID。"
confirm_stage "账户授权与 staging 隔离" "已确认授权范围与 staging/production 隔离，且没有进行任何写操作？"

stage "Worker、D1 与 R2 binding 核验"
say "本仓库 staging 配置只期望 binding 名 `DB`（D1）和 `RAW`（R2）；不要向本向导输入任何 ID 或对象键。"
open_url "https://developers.cloudflare.com/workers/runtime-apis/bindings/"
step "在本地编辑器只读查看 wrangler.jsonc 的 staging 段；在 dashboard 的 Worker Bindings 页面只读比对名称与目标资源。"
step "确认 staging D1 ID 已由账户所有者替换本地占位符，且 `DB` 不指向 production；确认 `RAW` 只指向 staging bucket。"
step "若绑定、ID 或资源边界不确定，选择 N；不要在 dashboard 或仓库中修改它们。"
confirm_stage "Worker/D1/R2 bindings 与占位符" "已只读确认 staging bindings 正确、实际 ID 不再为占位符，并且未接触 production？"

stage "Cloudflare Access 应用与策略核验"
say "只读检查 Access；不读取、显示或保存 Access JWT、service token、cookie、IdP 密钥或用户邮箱。"
open_url "https://developers.cloudflare.com/workers/configuration/cloudflare-access/"
step "在 Workers & Pages 中选择 staging Worker 后查看 Access，或按官方文档查看对应 Zero Trust Access application/policy。"
step "确认 `/api/admin/*` 受 staging Access 应用/策略保护；公开接口不被意外要求登录；策略/角色映射满足 viewer、editor、publisher 的最小权限设计。"
step "若 dashboard 实际路径与文档不同，只遵循官方文档，不猜测菜单或创建应用。"
confirm_stage "Access 应用与策略" "已只读确认 staging Access 范围、策略与角色最小权限，且未改动应用或策略？"

stage "可观测性、日志与预算告警核验"
say "只查看日志/指标/告警配置状态；不启动实时 tail、不导出日志、不发送测试通知，也不人为消耗用量。"
open_url "https://developers.cloudflare.com/workers/observability/logs/workers-logs/"
open_url "https://developers.cloudflare.com/billing/understand/billing-permissions/"
step "在 staging Worker 的 Observability/Logs 只读确认日志可用，并核对当前配置要求 `observability.enabled=true`。"
step "按 staging 告警证据包核对 Cron、source、daily、API 5xx 与 70%/90% 预算告警是否已有可读配置/所有者；缺项保持缺口。"
step "不得通过变更采样、告警接收人、Logpush、Cron、资源或账单来完成本阶段。"
confirm_stage "可观测性与告警" "已只读确认日志、告警与预算阈值状态，且没有启动通知、tail、导出或资源消耗？"

stage "公开域名、预算与发布开关核验"
say "不输入、打印或保存域名；仅记录该域名已获批准与否。不要变更 DNS、路由、Custom Domain、计划或付款。"
open_url "https://developers.cloudflare.com/workers/wrangler/configuration/"
step "只读确认 staging 公开域名/route 已由域名与预算负责人批准，并且与 production 分离；若没有域名，记录为缺口。"
step "在本地 staging 配置与已部署环境的只读页面中，分别确认 `ENABLE_CRON=false` 和 `ENABLE_AUTO_PUBLICATION=false`。"
step "Cron triggers 在配置中存在不等于获准启用；本阶段不部署、不迁移、不启用 Cron 或自动发布。"
confirm_stage "公开域名与两个发布开关" "已确认域名/route 获批且两个 staging 开关仍为 false，未改动 DNS、route、Cron 或发布？"
choose_budget_status

stage "签署缺口与不部署确认"
say "本阶段只汇总结论。任何 gap-or-unknown 都是 staging 演练或生产发布的停止条件，不能在此向导中绕过。"
step "将 evidence 文件中的 confirmed/gap-or-unknown 交给账户、预算、Access、数据/来源和发布责任人审阅。"
step "后续故障注入、三天 soak、导出/恢复演练必须获得其各自的书面授权，并按运行手册执行。"
confirm_stage "不部署确认" "确认本次仅完成只读前置检查，不会执行部署、资源创建/删除、配置写入、密钥操作、Cron 或自动发布？"

{
  printf '\n## 签署缺口\n\n'
  if (( ${#GAPS[@]} == 0 )); then
    printf '%s\n' '本次人工确认未报告缺口；这不是部署、演练或生产发布批准。仍需独立书面授权。'
  else
    printf '%s\n' '以下项目为 gap-or-unknown，必须在获授权的独立流程中处理：'
    for gap in "${GAPS[@]}"; do printf '%s\n' "- $gap"; done
  fi
  printf '\n%s\n' '以下外部签署不由本向导收集，默认仍为 pending-external：'
  printf '%s\n' '- staging account owner：资源隔离、binding 与变更窗口。'
  printf '%s\n' '- Access owner：应用、策略与测试身份。'
  printf '%s\n' '- budget owner：域名、成本上限与 Free/Paid 决定。'
  printf '%s\n' '- 数据/来源负责人和 publisher：后续演练、发布与恢复边界。'
  printf '\n%s\n' '声明：本向导未执行 Cloudflare CLI、远端读取/写入、部署、资源创建/删除、密钥处理、Cron 或自动发布操作。'
} >> "$EVIDENCE_FILE"

finish_preflight
say "只读前置检查已结束；证据已写入被 Git 忽略的本地文件：$EVIDENCE_FILE"
say "未执行部署或任何 Cloudflare 远端操作。"
